### PR TITLE
[querydsl-sql-codegen] Allow setting a catalogPattern in MetaDataExporter

### PR DESCRIPTION
**Pull request by kartoffelsup**
In order to extract data from multiple MySQL/MariaDB databases
which do not support schemas.

ref: https://jira.mariadb.org/browse/CONJ-16?focusedCommentId=29425&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-29425

### CODE REVIEW

**Comment by johnktims** [comment]
Sorry for the slow response. Would you mind rebasing on `master` and adding a test or two?

**Comment by kartoffelsup** [comment]
Done, but not sure if the tests are enough since H2 mem doesn't really do catalogs (catalog = database). Is there a IntegrationTest Facade with MySQL/MariaDB I could use?

**Comment by johnktims** [comment]
Something like this should work:
```
    @Test
    public void test_catalog() throws SQLException, ClassNotFoundException {
        Connections.initMySQL();
        Statement stmt = Connections.getStatement();
        stmt.execute("CREATE DATABASE database1");
        stmt.execute("CREATE DATABASE database2");

        // your test

        stmt.execute("DROP DATABASE database1");
        stmt.execute("DROP DATABASE database2");
    }
```

If you want to test locally, the easiest way to launch a properly-configured instance of MySQL is via docker: `docker-compose -f travis/docker-compose.yml up mysql`.

**Comment by kartoffelsup** [comment]
Thanks, I'll try that today :)

**Comment by johnktims** [comment]
Thanks @kartoffelsup!

**Comment by kartoffelsup** [comment]
Thanks for accepting/merging it :)

**Pull request merged**
