### PR TITLE
Rename Postgres to PostgreSQL

### LINKED ISSUE #1218: Rename Postgres references to PostgreSQL

### PR DESCRIPTION
**Pull request by johnktims**
Fixes #1218

### CODE REVIEW

**Comment by timowest** [comment]
@johnktims Thanks for the pull request! I took a quick glimpse, and it looked fine. I will do a more thorough review in the weekend.

**Comment by timowest** [comment]
@johnktims Did you update possible references in the reference docs? They are in the querydsl-docs module.

**Comment by johnktims** [comment]
I did not. I'll update the docs now.

**Comment by timowest** [comment]
@Shredder121 Maybe this should be merged first and the other SQL related PRs rebased on top of the changes?

**Comment by Shredder121** [comment]
Yes, I think that is a wise decision, although I haven't yet had the time to reinstall PostgreSQL(*haha*) to test this pull request.
Or did you already look at it?

**Comment by timowest** [comment]
I will still try it out in the weekend.

**Comment by timowest** [comment]
This is fine for me, @Shredder121 shall I merge it?

**Comment by Shredder121** [comment]
If it is fine for you then it is fine for me.
You can merge it then yes.

**Pull request merged**
