### PR TITLE
Rename <groups> property to <includedGroups> to prevent clashing

### PR DESCRIPTION
**Pull request by Shredder121**

### CODE REVIEW

**Comment by johnktims** [comment]
For more info: https://maven.apache.org/plugins/maven-javadoc-plugin/aggregate-mojo.html#groups

**Comment by johnktims** [comment]
Looks good to me. This doesn't need to be backported since #1538 wasn't backported.

**Comment by Shredder121** [comment]
But if it is backported, then this needs to be included.
But nice that it looks good. Let's see what Timo thinks.

**Comment by timowest** [comment]
Both PRs are not really bugfixes, so backporting is not really mandatory.

**Pull request merged**
