### PR TITLE
Travis configuration - revised (caching, intermittent failures, etc)

### PR DESCRIPTION
**Pull request by Shredder121**

### CODE REVIEW

**Comment by Shredder121** [comment]
Just a small test to see if it is actually that one artifact (so it's downloaded earlier) or if something else is wrong.
I'll switch on the debug output if it's something like that.

**Comment by Shredder121** [comment]
Restarting to see if it fails.

**Comment by Shredder121** [comment]
Restarting one last time.

**Comment by Shredder121** [comment]
It looks to be stable again?
What do you think?

**Comment by timowest** [comment]
Looks good

**Comment by robertandrewbain** [comment]
Looks good

**Comment by Taher-Ghaleb** [comment]
Hello,

Sorry, I know it's been a long time ago, but I am curious bundler was available since December 17, 2014, but I see you just enabled it in this pull request (which is in 2016). Any reasons, please? 

Thanks.

**Pull request merged**
