### PR TITLE
Add Robert to list of developers

### PR DESCRIPTION
**Pull request by timowest**

### CODE REVIEW

**Comment by johnktims** [comment]
Looks good. We'll need to update the website as well.

**Comment by johnktims** [comment]
And the documentation

**Comment by Shredder121** [comment]
Aww, why did you have to `push` him like that? :wink:
Shall I update the website?

**Comment by Shredder121** [comment]
And also to the list in the documentation?

**Comment by Shredder121** [comment]
This now looks good to me :wink:

**Pull request merged**
