### PR TITLE
Hide Projection constructors

### PR DESCRIPTION
**Pull request by timowest**
Related to #706

### CODE REVIEW

**Comment by timowest** [comment]
@Shredder121 Is this good to merge?

**Comment by Shredder121** [comment]
I only now just noticed.
`AppendingFactoryExpression` doesn't define a `serialVersionUID`.
I admit, its implementation might not change, but do you want to add it before it is released?

**Comment by timowest** [comment]
Added it right now.

**Comment by Shredder121** [comment]
Then these changes are also done.
So I shall merge this then.

**Pull request merged**
