### PR TITLE
Fix using multi query hints

### PR DESCRIPTION
**Pull request by MelleD**
#3109

### CODE REVIEW

**Comment by jwgmeligmeyling** [comment]
Please use a collection as value in the map instead. We don’t want a guava dependency in JPA.

also, what is the use case for this? Afaik jpa itself does not support multiple query hints for the same key.

**Comment by MelleD** [comment]
spring data and JPA support multiple values. 

Without multiple values the select looks different. Then just the last entry wins

In this example without multiple values you have n+1 issue. For first value looks like

First select n times
`select * from bar1 where id = ? `
`select * from bar1 where id = ? `
Second select 
`select * from bar2 where id IN (?,?...) `


With this fix both works (works currently in spring data)
First select 
`select * from bar1 where IN (?,?...) `
Second select 
`select * from bar2 where id IN (?,?...) `

In the parent pom there is already guava available, but ok i can remove the deps

**Comment by MelleD** [comment]
Here you can check in EJBQueryImpl in EclipseLink that the key can have multiple values

`
       static DatabaseQuery apply(String hintName, boolean shouldUseDefault, Object hintValue, DatabaseQuery query, ClassLoader loader, AbstractSession activeSession) {
            Hint hint = (Hint)mainMap.get(hintName);
            if (hint == null) {
                // unknown hint name - silently ignored.
                return query;
            }

            Map<String, Object> existingHints = (Map<String, Object>)query.getProperty(QUERY_HINT_PROPERTY);
            if (existingHints == null){
                existingHints = new HashMap<String, Object>();
                query.setProperty(QUERY_HINT_PROPERTY, existingHints);
            }
            existingHints.put(hintName, hintValue);

            return hint.apply(hintValue, shouldUseDefault, query, loader, activeSession);
        }
`

**Comment by MelleD** [comment]
@jwgmeligmeyling jwgmeligmeyling please have a look. Removed guava

**Comment by MelleD** [comment]
@jwgmeligmeyling friendly reminder, please have a look :)

**Comment by MelleD** [comment]
@jwgmeligmeyling friendly reminder, please have a look :)

**Comment by MelleD** [comment]
@sangyongchoi
@jwgmeligmeyling 
@meatballhat 
@rocketraman 

can someone have look?

**Pull request closed without merging**
