### PR TITLE
Fix projection wrapping

### PR DESCRIPTION
**Pull request by timowest**

### CODE REVIEW

**Comment by johnktims** [comment]
@timowest What was the issue here? I don't think I completely understand the rationale behind the change.

**Comment by timowest** [comment]
the serializer in Querydsl SQL expects flattened FactoryExpressions. The flattening happens in the SQLQueryMixin, here we are doing it explicitly since we use QueryMetadata directly.

**Comment by Shredder121** [comment]
Then to me it looks good.

**Comment by johnktims** [comment]
Agreed.

**Pull request merged**
