### PR TITLE
Improve normalization

### LINKED ISSUE #1224: Some strings are cutted when use literal mode
I've got a querydsl-sql (3.6.0) query like this

```java
		SQLQuery queryCheck = queryDslJdbcTemplateViaHibernateSession
				.getQuery()
				.from(isee159WsInpsAttestazioni_QSQL)
				.where(isee159WsInpsAttestazioni_QSQL.identificatoreRichiestaInps
						// .eq(typeAttestazione.getIdentificatoreRichiestaINPS()));
						.eq("INPS-ISET-0000-00000000A"));
                queryCheck.exists();
```
the output on jdbc side is

```sql
SELECT 1
FROM isee159_ws_inps_attestazioni isee159_ws_inps_attestazioni
WHERE isee159_ws_inps_attestazioni.identificatore_richiesta_inps = 'INPS-ISET0A' limit 1
```

the field is a string, as you can see the string is cutted on where clause **'INPS-ISET0A'**.
This behavior is only in literal mode, but I need it.

To put it in a nutshell I've made some tests and it sounds like '0' are packed inside the string.
Something like this:

* INPS-ISET-0000-12345678A  ==>  INPS-ISET-12345678A
* INPS-ISET-0000X00000000A ==>  INPS-ISET-0000X00000000A
* INPS-ISET-0000-00000000A  ==>  INPS-ISET0A

Please note that going inside the QueryBase object metadata.where has the right string while
metadata.self has the error. It sounds like a serialization issue.
Issue is not related to tables/query used. It happens on every query using where condition like that.
Any ideas?

### PR DESCRIPTION
**Pull request by johnktims**
Fixes #1224

### CODE REVIEW

**Comment by timowest** [comment]
@johnktims Thanks for the PR. Could you also add a test for quoted literals that have arithmetic expressions?

**Comment by timowest** [comment]
This PR contains also normalization related improvements https://github.com/querydsl/querydsl/pull/1220

**Comment by johnktims** [comment]
@timowest like
```java
assertEquals("'2 + 0hours'", Normalization.normalize("'2 + 0hours'"));
```
?

**Comment by johnktims** [comment]
Do you want to just close this PR and make the changes in #1220 ?

**Comment by timowest** [comment]
Maybe a literal like `a like '1 + 2 ' and b like '2 * 3'`

**Comment by timowest** [comment]
No, the other PR covers only precedence rules, not literal detection. That should be handled in another PR, so it's ok to do it here.

**Comment by Shredder121** [comment]
>a literal like `a like '1 + 2 '`

@timowest did you also want that space in the expression?

**Comment by timowest** [comment]
The space came accidently, but maybe both could be used.

**Comment by johnktims** [comment]
Are these normalizations really worthwhile? I imagine most people do their own computations before issuing the query instead of constructing a string of expressions, and I'm sure the database's query optimizer performs these sorts of optimizations anyway.

**Comment by timowest** [comment]
These optimizations are not performance optimizations but more two compress the result of serialization patterns which contain arithmetic expressions. It will make debugging the output easier if arithmetic expressions are handled.

**Comment by johnktims** [comment]
@timowest Should I close this in favor of #1252 ?

**Comment by Shredder121** [comment]
They have different targets.
One is master, the other QUERYDSL_3.

**Comment by johnktims** [comment]
Whoops. You're right.
I see that @timowest added a few more tests. Should I copy those over into this PR as well?

**Comment by timowest** [comment]
Yes, you can copy the tests. I have usually combined commits quite alot via
rebases or git commit --amend, so that might be also here a nice way.

**Comment by Shredder121** [comment]
Yes, just wanted to suggest that.

**Pull request merged**
