### PR TITLE
Integrate checkstyle

### LINKED ISSUE #1192: Integrate Checkstyle into the build

### PR DESCRIPTION
**Pull request by johnktims**
Fixes #1192

### CODE REVIEW

**Comment by Shredder121** [comment]
I am making a list that I'd like to (maybe) see integrated:

- [MissingCtor](http://checkstyle.sourceforge.net/config_coding.html#MissingCtor)

**Comment by timowest** [comment]
Here is something I've been trying out

```xml
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
        "-//Puppy Crawl//DTD Check Configuration 1.2//EN"
        "http://www.puppycrawl.com/dtds/configuration_1_2.dtd">

<module name="Checker">
  <property name="charset" value="UTF-8"/>
  <property name="fileExtensions" value="java, properties, xml"/>

  <!-- maximum file length 2000 lines -->
  <module name="FileLength"/>

  <!-- check that there are no tab characters in the file -->
  <module name="FileTabCharacter">
    <property name="eachLine" value="true"/>
  </module>

  <!-- no trailing whitespace -->
  <module name="RegexpSingleline">
    <property name="format" value="\s+$"/>
    <property name="message" value="Line has trailing spaces."/>
  </module>

  <module name="TreeWalker">

    <property name="cacheFile" value="${checkstyle.cache.file}"/>

    <module name="SuppressWarningsHolder"/>

    <!-- FIXME <module name="JavadocMethod"/> -->
    <!-- FIXME <module name="ConstantName"/> -->
    <module name="LocalFinalVariableName"/>
    <module name="LocalVariableName"/>
    <module name="MemberName"/>
    <module name="MethodName"/>
    <module name="PackageName"/>
    <module name="ParameterName"/>
    <module name="StaticVariableName"/>
    <module name="TypeName"/>

    <module name="IllegalImport"/> <!-- defaults to sun.* packages -->
    <module name="RedundantImport"/>
    <module name="UnusedImports"/>

    <module name="ImportOrder">
      <property name="groups" value="java,javax,org,com"/>
      <property name="ordered" value="false"/>
      <property name="separated" value="true"/>
      <property name="option" value="top"/>
    </module>

    <!-- FIXME <module name="LineLength"> -->
    <!-- FIXME <module name="MethodLength"/> -->

    <module name="EmptyForIteratorPad"/>
    <module name="MethodParamPad"/>
    <module name="NoWhitespaceAfter"/>
    <module name="NoWhitespaceBefore"/>
    <module name="ParenPad"/>
    <module name="TypecastParenPad"/>
    <module name="WhitespaceAfter"/>
    <module name="WhitespaceAround"/>

    <module name="ModifierOrder"/>
    <module name="RedundantModifier"/>

    <module name="EmptyBlock"/>
    <module name="LeftCurly"/>
    <module name="NeedBraces"/>
    <module name="RightCurly"/>

    <module name="EmptyStatement"/>
    <module name="EqualsHashCode"/>
    <module name="IllegalInstantiation"/>
    <!-- FIXME <module name="InnerAssignment"/> -->
    <module name="RedundantThrows"/>
    <module name="SimplifyBooleanExpression"/>
    <!-- FIXME <module name="SimplifyBooleanReturn"/> -->

    <module name="FinalClass"/>
    <!-- FIXME <module name="HideUtilityClassConstructor"/> -->
    <module name="InterfaceIsType"/>
    <module name="ArrayTypeStyle"/>
    <module name="UpperEll"/>

  </module>

  <module name="SuppressWarningsFilter"/>
  <!-- FIXME <module name="UniqueProperties"/> -->

</module>
```

**Comment by Shredder121** [comment]
I really like your `ImportOrder` one, I wasn't yet at the category of checks.
Just wanted to say that.

**Comment by timowest** [comment]
Shall I merge this? We can extend the configuration via additional PRs.

**Comment by johnktims** [comment]
I wish we had implemented some basic checks, but I guess it's fine to just merge the configuration now and gradually add checks later on.

**Pull request merged**
