### PR TITLE
Add a profile that skips validation

### PR DESCRIPTION
**Pull request by Shredder121**
This might be useful for end users, since there could be lots of time wasted in the checks.

Let me know what you think.

### CODE REVIEW

**Comment by timowest** [comment]
Looks good

**Comment by Shredder121** [comment]
Do you think we can also use it with Travis, as initial install?

**Comment by timowest** [comment]
> Do you think we can also use it with Travis, as initial install?

Makes sense.

**Comment by Shredder121** [comment]
Do you want to quit the build early if there are issues?
Or do you want to have it in the verification process?

**Comment by Shredder121** [comment]
Because if you want it to quit the build early, then it's better to leave Travis the way it is.

**Comment by Shredder121** [comment]
I noticed that for Travis the time doesn't really matter, since it has to do a two pass anyway.
So I suppose that's it then? Let me know what you think.

**Comment by johnktims** [comment]
This looks good to me.

**Pull request merged**
