### PR TITLE
Update copyright

### PR DESCRIPTION
**Pull request by timowest**

### CODE REVIEW

**Comment by timowest** [comment]
@Shredder121  @johnktims Which one do you prefer

* Copyright 2015, The Querydsl Team (http://www.querydsl.com/team)
* Copyright 2015, Querydsl Team (http://www.querydsl.com/team)
* Copyright 2015, the Querydsl Team (http://www.querydsl.com/team)

**Comment by johnktims** [comment]
The first one is fine with me.

**Comment by Shredder121** [comment]
Haha, yes I also agree, the first one.

**Comment by johnktims** [comment]
I noticed the scala files are still under Mysema. Can those be updated?

**Comment by timowest** [comment]
Yes. The should be updated as well.

**Pull request merged**
