### PR TITLE
DB2 support

### PR DESCRIPTION
**Pull request by timowest**
Fixes https://github.com/querydsl/querydsl/issues/647

### CODE REVIEW

**Comment by timowest** [comment]
@Shredder121 Is this ok to merge or do you still see things to improve?

**Comment by Shredder121** [comment]
I see some test failures, do you see that as well?
I am currently looking through the [list of built in functions](http://www-01.ibm.com/support/knowledgecenter/SSEPGG_10.5.0/com.ibm.db2.luw.sql.ref.doc/doc/r0011043.html?cp=SSEPGG_10.5.0%2F2-12-4) to see if we could improve anything.

The failing date operation week() has a *_ISO counterpart(as for most date/time operations), so shall we exclude that or use the *_ISO counterpart? (I think that excluding is a safer, more consistent approach)

**Comment by timowest** [comment]
@Shredder121 Which failures do you refer to? I am able to run the DB2 suites without issues against DB2 Enterprise 10.1.2 on Linux.

**Comment by Shredder121** [comment]
I have a breakpoint hit for the following trace.
```
"main"
com.mysema.query.QueryExecution.runFilterQueries(QueryExecution.java:136)
com.mysema.query.QueryExecution.runDateTests(QueryExecution.java:303)
com.mysema.query.SelectBase.StandardTest(SelectBase.java:1368)
sun.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java)
sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
java.lang.reflect.Method.invoke(Method.java:606)
org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:76)
org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
org.junit.runners.ParentRunner$3.run(ParentRunner.java:193)
org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:52)
org.junit.runners.ParentRunner.runChildren(ParentRunner.java:191)
org.junit.runners.ParentRunner.access$000(ParentRunner.java:42)
org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:184)
org.junit.runners.ParentRunner.run(ParentRunner.java:236)
org.junit.runners.Suite.runChild(Suite.java:128)
org.junit.runners.Suite.runChild(Suite.java:24)
org.junit.runners.ParentRunner$3.run(ParentRunner.java:193)
org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:52)
org.junit.runners.ParentRunner.runChildren(ParentRunner.java:191)
org.junit.runners.ParentRunner.access$000(ParentRunner.java:42)
org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:184)
org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:28)
org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:31)
org.junit.runners.ParentRunner.run(ParentRunner.java:236)
org.junit.runners.Suite.runChild(Suite.java:128)
org.junit.runners.Suite.runChild(Suite.java:24)
org.junit.runners.ParentRunner$3.run(ParentRunner.java:193)
org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:52)
org.junit.runners.ParentRunner.runChildren(ParentRunner.java:191)
org.junit.runners.ParentRunner.access$000(ParentRunner.java:42)
org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:184)
org.junit.runners.ParentRunner.run(ParentRunner.java:236)
org.junit.runner.JUnitCore.run(JUnitCore.java:157)
org.junit.runner.JUnitCore.run(JUnitCore.java:136)
org.apache.maven.surefire.junitcore.JUnitCoreWrapper.createRequestAndRun(JUnitCoreWrapper.java:141)
org.apache.maven.surefire.junitcore.JUnitCoreWrapper.executeEager(JUnitCoreWrapper.java:114)
org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:86)
org.apache.maven.surefire.junitcore.JUnitCoreProvider.invoke(JUnitCoreProvider.java:134)
org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
```

the f is week(e.datefield) = 6, so it is the `DateConstant` one of `src/test/java/com/mysema/query/MatchingFiltersFactory.java:87`.


For some reason, this also happens with SQLite, it might be a timezone issue (in which case it's fine, since it does work for you).

**Comment by timowest** [comment]
@Shredder121 So this is good to merge then? I will try to start with the 4.0 changes as soon as the remaining PRs are merged.

**Comment by Shredder121** [comment]
for reference: [Data types that map to database data types in Java applications](http://www-01.ibm.com/support/knowledgecenter/SSEPGG_9.7.0/com.ibm.db2.luw.apdv.java.doc/src/tpc/imjcc_rjvjdata.html).

**Comment by timowest** [comment]
Ok, I will improve the type mappings

**Comment by timowest** [comment]
Type support should be better now for DB2 and also other dialects.

**Comment by timowest** [comment]
I created an issue for the SQL keywords https://github.com/querydsl/querydsl/issues/1114

@Shredder121 Do you think we can merge this now?

**Comment by Shredder121** [comment]
Yes, I will merge this.

**Pull request merged**
