### PR TITLE
Add serialization test utility

### PR DESCRIPTION
**Pull request by timowest**
extracted from this backport https://github.com/querydsl/querydsl/pull/1239

### CODE REVIEW

**Comment by johnktims** [comment]
You should be able to remove `RelationalPathTest#serialize` and use this instead.

**Comment by timowest** [comment]
Ok, I made some where further changes.

**Comment by timowest** [comment]
@johnktims Is the updated version fine?

**Comment by johnktims** [comment]
This looks good to me.

**Pull request merged**
