### PR TITLE
Extend Hibernate dialects

### PR DESCRIPTION
**Pull request by timowest**
Introduces Hibernate dialects which extend the official database specific Hibernate dialects with Querydsl based function definitions with date/time operations and other functionality that is not correctly defined in the original dialects.

### CODE REVIEW

**Comment by Shredder121** [comment]
There is a shorthand for registering functions.
You could use `getFunctions().putAll(DialectSupport.createFunctions(templates))`, since the only thing the registerFunction does differently is converting the name to lowercase.

We already use lowercase function names, so it could be used.
Up to you whether you incorporate it though.

**Comment by timowest** [comment]
That's a great suggestion, I will try it.

**Comment by Shredder121** [comment]
Looks good to me.
Restarted the Scala build.

**Comment by johnktims** [comment]
Looks good.

**Pull request merged**
