### PR TITLE
Use yaml list notation in pullapprove config

### PR DESCRIPTION
**Pull request by Shredder121**
![YAML parse error][]
I noticed that the configuration wasn't quite right.

Let's see if this one is better.

[YAML parse error]: https://cloud.githubusercontent.com/assets/4105066/16568314/01600faa-4229-11e6-9e4a-19c8a5ef0793.png

### CODE REVIEW

**Comment by Shredder121** [comment]
>  code-review/pullapprove — Invalid .pullapprove.yml, check pullapprove.com for details

Hmm yeah.. this is a problem :laughing:
Can Timo override the merge?

**Comment by davegaeddert** [comment]
@Shredder121 just thought I'd jump in here with one specific comment -- the `teams` should also be a list:
```yaml
reviewers:
  - name: querydsl team
    teams:
      - developers
    required: 1
```

**Comment by Shredder121** [comment]
@davegaeddert Ah, thanks for the tip.
I'm just going with what the UI told me, and a YAML parser.
Must have missed that that is also a list, much appreciated.

**Comment by timowest** [comment]
I also can't override it

**Comment by Shredder121** [comment]
You could disable 'include administrators' for a bit.
![include administrators][]

[include administrators]: https://cloud.githubusercontent.com/assets/4105066/16596545/b7d35942-42f4-11e6-8f3f-9a906a08cac8.png

**Pull request merged**
