### PR TITLE
Remove type(?) expression customizations

### PR DESCRIPTION
**Pull request by timowest**
Related to #1123 

When the master branch contains the Querydsl 4 changes this PR should be ported also to be applied to the master branch.

### CODE REVIEW

**Comment by Shredder121** [comment]
This pull request looks good, the same goes for the forward ported one.

Shall we in the future (when PRs are some time apart) look at the oldest pull request, and merge them both when 2 days have passed?
What do you think?

**Comment by timowest** [comment]
Yes. That sounds fine.

**Comment by Shredder121** [comment]
Sorry for the delay.
I think we can merge these now?

**Comment by timowest** [comment]
Yes.

**Pull request merged**
