### PR TITLE
#1429 JPQL generation causes issues with hibernate query caching

### PR DESCRIPTION
**Pull request by l30thelion**
Please review potential solution for #1429 and #1413

### CODE REVIEW

**Comment by timowest** [comment]
There seem to be a few backwards incompatible signature changes in the code. We can do those only in major releases.

**Comment by l30thelion** [comment]
My proposed solution required the change of the method getConstantToLabel to getLabelToConstant to ensure that the constant labels are unique thereby avoiding the Hibernate bug.  I'm using the fix on my project at work.........this solves the issue, but is it a proper solution in your opinion?  Thanks for taking the time to reply!

**Comment by timowest** [comment]
Based on my short review it looks like a proper solution, but for backwards compatible reason it can't be applied to a minor or patch release.

**Comment by jwgmeligmeyling** [comment]
The PR is outdated and QueryDSL 3.x is no longer maintained. This fix would need to be updated.

**Pull request closed without merging**
