### PR TITLE
Use AbstractQuery & Query division consistently

### LINKED ISSUE #612: Use AbstractQuery & Query division consistently
querydsl-collections 
* AbstractCollQuery & CollQuery

querydsl-hibernate-search 
* AbstractSearchQuery (TODO) & SearchQuery

querydsl-jdo 
* AbstractJDOQuery & JDOQuery
* AbstractSQLQuery & JDOSQLQuery

querydsl-jpa 
* AbstractHibernateQuery & HibernateQuery
* AbstractHibernateSQLQuery & HibernateSQLQuery
* AbstractJPAQuery & JPAQuery
* AbstractJPASQLQuery & JPASQLQuery

querydsl-lucene(3|4)
* AbstractLuceneQuery & LuceneQuery

querydsl-mongodb
* MongodbQuery -> AbstractMongodbQuery (TODO)

querydsl-sql
* AbstractSQLQuery & SQLQuery

### PR DESCRIPTION
**Pull request by timowest**
Fixes #612

### CODE REVIEW

**Comment by Shredder121** [comment]
I didn't know we were already at issue 1612 ;)

**Comment by timowest** [comment]
Yes, a small accident.

**Comment by Shredder121** [comment]
This looks good in my opinion, so now all the modules have the same structure?

Do you think it is necessary to also equalize the `abstract` modifier?

**Comment by timowest** [comment]
I equalized now also the abstract modifier usage. The structure should be now more consistent.

**Comment by Shredder121** [comment]
Yes, I think it is now good.

I'll merge it when the build completes.

**Pull request merged**
