### PR TITLE
Changed "scanPackage" method implementation. Used Reflections API.

### PR DESCRIPTION
**Pull request by bcubk**
Fixed implementation of ClassPathUtils to support 'zip' files. I used the method 'safeClassForName' to initialize the retrieved classes manually. The lib doesn't initialize the classes. 
Issue: #1235

### CODE REVIEW

**Comment by bcubk** [comment]
Sorry, I did a mistake

**Comment by Shredder121** [comment]
Just wondering, if you don't mind me asking, what IDE do you use?

**Comment by bcubk** [comment]
First, I was confused about the results of the Travis build. After I checked my code and found a tremendous bug. That's the reason why I closed this PR. I'm using IntelliJ IDEA.

**Comment by Shredder121** [comment]
That is fine, I just noticed the change in the import order (I thought I devised a pretty 'universal'-ish one).

**Pull request closed without merging**
