### PR TITLE
added SQL Server 2016 support to SQLTemplatesRegistry

### PR DESCRIPTION
**Pull request by lpandzic**
SQL Server 2016 returns major version 13.
@Shredder121 , can you please take a look?

### CODE REVIEW

**Comment by Shredder121** [comment]
I will, thanks for the PR.

**Comment by timowest** [comment]
Looks good

**Comment by lpandzic** [comment]
Can someone please trigger rebuild, it seems something random failed?

**Comment by Shredder121** [comment]
Yeah, Travis killed our configuration, we're moving to a docker based build.
Apologies for the inconvenience.

**Comment by Shredder121** [comment]
Might also need to backport this.. for the 3.7.5 milestone

**Pull request merged**
