### PR TITLE
Add more assertions

### PR DESCRIPTION
**Pull request by timowest**

### CODE REVIEW

**Comment by Shredder121** [comment]
To me it looks good.
@johnktims what about you?

**Comment by johnktims** [comment]
If you search for "assertions" there are several comments that say "// TODO : assertions". Also, searching for "System.out.print" reveals a few more places where assertions could be made.

**Comment by timowest** [comment]
I'll try to add more assertions for the compilation cases.

**Comment by johnktims** [comment]
There are some more assertions that could be added but I think this is good enough for now.

**Comment by Shredder121** [comment]
Agreed.

**Pull request merged**
