### PR TITLE
Replace Puppet with Shell provisioner

### PR DESCRIPTION
**Pull request by timowest**
Support
- [x] MySQL 5.6
- [x] PostgreSQL 9.3
- [x] Mongodb
- [ ] CUBRID
- [ ] Firebird
- [ ] Oracle XE

### CODE REVIEW

**Comment by johnktims** [comment]
What do you think about adding Mongo to the list?

**Comment by Shredder121** [comment]
:+1:
I think that would be good.

**Comment by johnktims** [comment]
This might be a better approach to adding mongo support: https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo

**Comment by johnktims** [comment]
We're using docker to manage the test environments.

**Pull request closed without merging**
