### PR TITLE
Revert "Querydsl 4.2.0"

### PR DESCRIPTION
**Pull request by timowest**
Reverts querydsl/querydsl#2260

### CODE REVIEW

**Comment by Shredder121** [comment]
What's up?

**Comment by timowest** [comment]
The latest merged PRs had backwards compatibility issues that need to be resolved before releasing.

**Comment by Shredder121** [comment]
Would you do that?
(which changes in particular?)

**Comment by timowest** [comment]
Could you approve this to have the release version reverted before we do another attempt?

**Comment by johnktims** [comment]
looks good

**Pull request merged**
