### PR TITLE
Improve Scala usage

### PR DESCRIPTION
**Pull request by timowest**
Changes are
* remove unnecessary semicolons
* follow Scala conventions in method invocation syntax
* fix lambda usage
* use file compilation instead of interpreter based compilation

backport https://github.com/querydsl/querydsl/pull/1258

### CODE REVIEW

**Comment by timowest** [comment]
This seems to have stabilized, I have now replaced all interpreter based compilation with another compliation variant.

**Comment by timowest** [comment]
@Shredder121 @johnktims Could one of you take a look at this? The `CompilerTestUtils` changes are the most significant. After this has been merged, the querydsl-scala failures should be (temporarily?) a thing of the past.

**Comment by Shredder121** [comment]
To me it looks good, there are a few `reset()` methods that could be called (can't quite recall where I saw them though) but they are merely for resetting, and not for explicitly 'closing' a resource.

So I think it looks good. The Scala syntax is quite new to me though, but it doesn't read all that bad. At times.

**Comment by timowest** [comment]
Ok, I will prepare the backport tomorrow.

**Pull request merged**
