### PR TITLE
insertion order for JPA query hints

### PR DESCRIPTION
**Pull request by encircled**
Some JPA hints are order-dependent

### CODE REVIEW

**Comment by timowest** [comment]
Are you sure ArrayListMultimap does what you want? It uses a HashMap internally for key -> values mapping. The only difference is that the values for a given key are iterated in insertion order.

**Comment by encircled** [comment]
Insertion order of values is exactly what we need, PR description is a bit misleading.
The initial problem is that eclipselink requires hints for nested fetch joins and there is a bug (or feature), that `parent.child` fetch hint must be before `child.nestedChild` one.

**Comment by timowest** [comment]
Look at the javadoc for ArrayListMultimap. Iteration order of keys comes from HashMap, iteration order of values for a given key comes from ArrayList.

**Comment by encircled** [comment]
I know, for fetch joins in eclipse there is one hint (key) and multiple values

**Comment by timowest** [comment]
Ok, sorry, I misunderstood. parent.child and child.nestedChid are the values?

**Comment by encircled** [comment]
Yes

**Comment by Shredder121** [comment]
A `String` hashcode is probably still very good, so maybe a `LinkedHashMultimap` is a better pick?

**Comment by Shredder121** [comment]
Looks good to me as well, other than that.
Just want to hear an opinion.

**Comment by encircled** [comment]
LinkedHashMultimap uses Set for hint values, it will break the order

**Comment by Shredder121** [comment]
There are Set implementations that preserve insertion order.

@timowest What is your view?

**Comment by encircled** [comment]
Yes, but you can't change used implementation in LinkedHashMultimap, can you?

**Comment by Shredder121** [comment]
The used implementation preserves insertion order.
The Javadoc is very specific about this:

> Implementation of Multimap that does not allow duplicate key-value entries and that returns collections **whose iterators follow the ordering in which the data was added to the multimap**.

Emphasis mine.
This means insertion order.

Or is there something I am missing?

http://google.github.io/guava/releases/snapshot/api/docs/com/google/common/collect/LinkedHashMultimap.html

**Comment by encircled** [comment]
Insertion order of root keys is preserved indeed, but what do I need is insertion order of associated values  (nested collections)

**Comment by Shredder121** [comment]
But that is preserved:
https://github.com/google/guava/wiki/NewCollectionTypesExplained#implementations-1

All documentation I find points to that, and a quick test also confirms that.

@timowest you can merge this if you want.

image

**Comment by encircled** [comment]
Sorry, you are right. That Set has name WrappedSet, didn't mention it uses LinkedHashSet as a delegate.

**Comment by timowest** [comment]
LinkedHashMultimap might be better.

**Comment by encircled** [comment]
Indeed, I will change it

**Comment by timowest** [comment]
Could you squash the commits, then we're good

**Comment by encircled** [comment]
done

**Comment by timowest** [comment]
@encircled Thanks a lot for the contribution!

**Pull request merged**
