### PR TITLE
Remove dots from MDC log fields.

### LINKED ISSUE #1941: QueryDSL MDC logging fields contain dots
QueryDSL MDC logging fields contain dots in the field names. All logging infrastructure based on ELK (Elasticsearch, Logstash, Kibana) will require the dots in fields to be removed when upgrading to 2.0 (see: https://www.elastic.co/guide/en/elasticsearch/reference/current/breaking_20_mapping_changes.html#_field_names_may_not_contain_dots).

### PR DESCRIPTION
**Pull request by utwyko**
Fixes #1941

### CODE REVIEW

**Comment by timowest** [comment]
Maybe the backwards compatibility check is too strict here?

**Comment by Shredder121** [comment]
Why is it too strict? You shouldn't change stuff in public members that are not backwards compatible.
So, the best we can do I think is push this back to a minor release.

**Comment by Shredder121** [comment]
So, about the minor release.
@querydsl/developers Do you think we should include this is 4.2?

**Comment by Shredder121** [comment]
The easiest would be to do this in Querydsl 5.
Just so we can be sure we're not breaking things accidentally.

Then we'll break things on purpose, but then it will at least be expected with a major version bump.

**Comment by jwgmeligmeyling** [comment]
Applied to master.

**Pull request closed without merging**
