### PR TITLE
Integrate Coveralls and separately build Scala module on Travis

### PR DESCRIPTION
**Pull request by johnktims**
Closes #1548 and #1540

### CODE REVIEW

**Comment by johnktims** [comment]
Closes #1548 and #1540

**Comment by timowest** [comment]
Looks good

**Comment by Shredder121** [comment]
I think `closes xxx` messages should go in the PR description. Or if you found otherwise could you link that?

**Comment by timowest** [comment]
What's the relation of this PR to the other two related Scala and Coveralls PRs?

**Comment by Shredder121** [comment]
This is the successor, it includes both.

**Comment by johnktims** [comment]
Sorry for the confusion @timowest. I didn't intend to open this PR. I was testing the combination of these two features in my fork and GitHub tricked me into opening the PR on querydsl instead of my fork, but since it's here I'll just use it to close the other two PRs.

**Comment by johnktims** [comment]
I renamed `-pl` to `--projects` as Ruben suggested in #1548.

**Comment by Shredder121** [comment]
Could you backport this, since the versions used in the examples there are also old?

**Comment by Shredder121** [comment]
I suppose merging this is good now?

**Comment by johnktims** [comment]
Yes. I'm backporting it right now.

**Comment by Shredder121** [comment]
So I am merging these now.

**Pull request merged**
