### PR TITLE
Add missing IgnoreCaseUnsupportedException to the lucene modules

### PR DESCRIPTION
**Pull request by Shredder121**
I seem to have forgotten to update this.

### CODE REVIEW

**Comment by Shredder121** [comment]
Who wants to backport this? :wink:

**Comment by timowest** [comment]
Looks good.

**Comment by Shredder121** [comment]
I didn't see `LIKE_ESCAPE` so I figured it would be okay to delegate to `illegal operation` for `LIKE_ESCAPE_IC`.

**Comment by timowest** [comment]
Yes, that makes sense.

**Comment by johnktims** [comment]
Looks good.

**Pull request merged**
