### PR TITLE
Switch to jdk6 for tests

### LINKED ISSUE #1169: Make sure that the code is compatible with JDK 1.6
Travis builds with different JDK versions doesn't cover this requirement, since Querydsl can't be built anymore with JDK 1.6. Still the result should be compatible with JDK 1.6.

This looks like a promising solution http://eclipsesource.com/blogs/2014/05/09/ensure-class-library-compatibility-in-a-maven-build/

### PR DESCRIPTION
**Pull request by timowest**
Fixes #1169

### CODE REVIEW

**Comment by Shredder121** [comment]
Sun JDK6 is not provided.
You could use OpenJDK 6 instead.

**Comment by Shredder121** [comment]
Hmm, it still compiles the project.

Then the maven plugin signature check sounds like a good solution.
Shall we close this then?

**Comment by Shredder121** [comment]
It still tries to compile the project using JDK6.
I think that the Maven plugin that checks the signatures is a good alternative.

It also runs client-side, so it's validated early.

**Comment by timowest** [comment]
Ok, let's try that instead.

**Pull request closed without merging**
