### PR TITLE
Optimize surefire config in travis profile

### PR DESCRIPTION
**Pull request by timowest**

### CODE REVIEW

**Comment by timowest** [comment]
@Shredder121 Could you take a look at this PR? It should make the handling of Travis logs simpler.

**Comment by Shredder121** [comment]
There is also a `<usefile>` parameter, do you know by chance if travis outputs the console? it looks like it.
I think disabling as much output as possible could(?) help.

**Comment by Shredder121** [comment]
Other than that it looks good.

**Comment by timowest** [comment]
Good catch. `<usefile>` disabled `<printSummary>false</printSummary>`, when I tried it, that's why I didn't include it.

**Comment by Shredder121** [comment]
If that is the case, then it doesn't matter.
A little more I/O isn't that bad.
In my opinion it is good to merge.

**Pull request merged**
