### PR TITLE
Querydsl 4.2.1

### PR DESCRIPTION
**Pull request by timowest**

### CODE REVIEW

**Comment by Shredder121** [comment]
hmm build failures?
(at least the output itself looks alright)

**Comment by Shredder121** [comment]
Core, codegen, apt?

Also, shouldn't it be --also-make (-am) not --also-make-dependents (-amd)?
Or did the quoting mean it didn't end up in the command line correctly?

**Comment by timowest** [comment]
I will clean it up, once the build passes

**Comment by timowest** [comment]
@Shredder121 Ready for merge?

**Comment by Shredder121** [comment]
👍 sorry figured I'd wait for the ping but missed it.

**Comment by timowest** [comment]
Released

**Pull request merged**
