### PR TITLE
Add Override annotation

### LINKED ISSUE #1223: com.querydsl.codegen.BeanSerializer.addToString doesn't generate @Override annotation on method
com.querydsl.codegen.BeanSerializer.addToString doesn't generate @Override annotation on method which leads to compiler warnings.

### PR DESCRIPTION
**Pull request by timowest**
Fixes #1223

### CODE REVIEW

**Comment by timowest** [comment]
@Shredder121 Could you take a look at this one? Should be quite straightforward.

**Comment by Shredder121** [comment]
I took the liberty to add a test case, is it okay?

**Comment by timowest** [comment]
Sure.

**Comment by Shredder121** [comment]
It now looks good. I will merge it.

**Pull request merged**
