### PR TITLE
fixed codegen-utils artifactId in bom

### LINKED ISSUE #3031: querydsl-codegen-utils:5.0.0 is missing in maven central
## Observed vs. expected behavior
Hi, **com.querydsl:querydsl-codegen-utils:jar:5.0.0** which is mentioned in [querydsl-bom](https://search.maven.org/artifact/com.querydsl/querydsl-bom/5.0.0/pom) is not present in maven central or deployed in maven central .  But rather **com.querydsl:codegen-utils:5.0.0** is. Can you please let us know if it was by mistake or intended? 

## Steps to reproduce
Search for com.querydsl:codegen-utils:5.0.0 in Maven central

Querydsl version: 5.0.0

### PR DESCRIPTION
**Pull request by lpandzic**
Fixes #3031

### CODE REVIEW

**Comment by jwgmeligmeyling** [comment]
Thanks! 👍🏻

**Comment by Sachpat** [comment]
Thanks @lpandzic . WIll there be a new release of querydsl BOM with this?

**Comment by lpandzic** [comment]
Yes, but when I do not know. @jwgmeligmeyling do you have any idea?

**Comment by jwgmeligmeyling** [comment]
I think this + OSGI + japicmp is enough for a next release. When I've merged all branches, Ill ask John to do the release.

**Comment by Sachpat** [comment]
Thanks @jwgmeligmeyling !

**Pull request merged**
