### PR TITLE
Fixed NEXTVAL Operator for MS SQLServer (starting with 2012)

### PR DESCRIPTION
**Pull request by tpuica**
Hi,
The nextval operator is wrong for SQL Server. It should be "next value for ". 
See https://docs.microsoft.com/en-us/sql/t-sql/functions/next-value-for-transact-sql

Thanks.
theodor

### CODE REVIEW

**Comment by Shredder121** [comment]
So would the correct syntax be `next value for myseq`?
If that's correct, could you update that?

https://github.com/querydsl/querydsl/blob/master/querydsl-sql/src/test/java/com/querydsl/sql/SQLServer2012TemplatesTest.java#L106-L110

**Comment by Shredder121** [comment]
Could you also link the relevant documentation for completeness sake?

**Comment by Shredder121** [comment]
Also, I think something went wrong on our end, if you could also change it to be the more concise `assertSerialized`?
```java
assertSerialized(nextval, "next value for myseq");
```

**Comment by tpuica** [comment]
Test updated. 
It is though unclear for me where or how to link the relevant documentation (the link to the Microsoft documentation was in the pull request comment from the beginning)

**Comment by Shredder121** [comment]
Ah, then disregard that, sorry.

**Comment by timowest** [comment]
Looks good

**Pull request merged**
