### PR TITLE
Add SELECT FOR UPDATE support

### LINKED ISSUE #1446: sqlQuery.forUpdate() does not work on SQLServer
In case we have an SQLQuery and call query.forUpdate(), that does not work on SQLServer.

The reason is that while all other databases use the syntax:

    SELECT... FROM...WHERE... FOR UPDATE

SQLServer uses the following:

   SELECT ... FROM ... WITH (UPDLOCK) ... WHERE...

That means that pessimistic lock can be done with a Table Hint in SQLServer.

There is a class called SQLServerQuery and the hint can be added easily there. However, by using that class, the code will be database dependent.

It would be nice if sqlQuery.forUpdate() added a table hint instead of QueryFlag in case of SQLServer so the client code could be database independent.

### PR DESCRIPTION
**Pull request by timowest**
Fixes #1446

### CODE REVIEW

**Comment by balazs-zsoldos** [comment]
That was fast, thank you!

The problem is this modification only works if there is no WHERE clause in the SQL statement. WITH must come in SQLServer after FROM or the last JOIN.

E.g.:

    SELECT a.x, b.x  FROM a INNER JOIN b ON a.x = b.x __WITH (UPDLOCK)__ WHERE a.y = ?

The generated SQL based on the modification throws a syntax error:

    SELECT a.x, b.x  FROM a INNER JOIN b ON a.x = b.x  WHERE a.y = ? __WITH (UPDLOCK)__

It is very common that there is at least one predicate in WHERE clause to filter the results when someone wants to use pessimistic locking. I suggest that the Unit tests should contain a where part as well. E.g.:

    query().from(survey).forUpdate().select(survey.id).where(suervey.gt(-1)).fetchOne();

In my code, I used the following line in case of SQLServer instead of _.forUpdate()_ (after analyzing SQLQuery class):

    query.addJoinFlag(" with (" + SQLServerTableHints.UPDLOCK.name() + ")", Position.END);

I cannot see how this could be added by only changing the SQLTemplates class yet.

**Comment by timowest** [comment]
The position of the flag is now also customizable and is fixed for MSSQL.

**Comment by balazs-zsoldos** [comment]
That was fast again!!! I guess line 86 and 87 in SQLServerTemplates is not necessary anymore:

     add(SQLOps.FOR_UPDATE, "\nwith (updlock)");

**Comment by timowest** [comment]
@balazs-zsoldos We need both the customization of the position and the template of the operation.

**Comment by johnktims** [comment]
This looks good to me.

**Comment by balazs-zsoldos** [comment]
For me, too. Waiting for the new release ;-)

**Comment by Shredder121** [comment]
Yes looks good, I'll merge this.

**Pull request merged**
