### PR TITLE
Code cleanup

### PR DESCRIPTION
**Pull request by timowest**

### CODE REVIEW

**Comment by johnktims** [comment]
I think you're missing an `@Override` on `AbstractHibernateSQLQuery#clone`.

**Comment by Shredder121** [comment]
What can be done under 'code cleanup'?
Trailing whitespace, imports?
Or what did you have in mind?

**Comment by timowest** [comment]
Trailing whitespace and fixing imports sounds good.

**Comment by johnktims** [comment]
Is there anything else you'd like to clean up here?

**Comment by timowest** [comment]
I think it's fine for now

**Comment by timowest** [comment]
@johnktims @Shredder121 Is this ok to merge?

**Comment by johnktims** [comment]
I think it's fine.

**Comment by Shredder121** [comment]
As I said, what should be included(what is the scope)?
We could also remove unused/duplicate tests, and I wonder, does eclipse configuration get outdated?

**Comment by johnktims** [comment]
Too late ;)

**Comment by johnktims** [comment]
There shouldn't be any eclipse configuration files checked in. Is that what you're referring to, @Shredder121 ?

**Pull request merged**
