### PR TITLE
Fix orderby handling

### LINKED ISSUE #1846: ERROR: for SELECT DISTINCT, ORDER BY expressions must appear in select list
The following code:
```java
JPAQuery query = new JPAQuery(em);
query.distinct();
query.from(QPlayer.player);
query.orderBy(new OrderSpecifier(Order.ASC, QPlayer.player.team.id));
query.list(QPlayer.player, QPlayer.player.team.id);
```

generates wrong JPQL:
```sql
SELECT DISTINCT player,
                player.team.id
FROM Player player
LEFT JOIN player.team AS player_team
ORDER BY player_team.id ASC
```
In code we are using the same expression `QPlayer.player.team.id` two times: in [order by] and [select] sections. But the resulting query has different expressions:
- in [select] section we have `player.team.id`
- but in [order by] it is collapsed and looks differently: `player_team.id`

Wrong JPQL leads to wrong SQL:
```sql
SELECT DISTINCT player0_.team_id AS col_0_0_,
                player0_.id AS col_1_0_,
                ...
FROM Player player0_
LEFT OUTER JOIN Team team1_ ON player0_.team_id=team1_.id
ORDER BY team1_.id ASC
```
And this query cannot be executed due to error

> ERROR: for SELECT DISTINCT, ORDER BY expressions must appear in select list

_We are using QueryDSL **v.3.6.8**_

### PR DESCRIPTION
**Pull request by timowest**
Fixes #1846

### CODE REVIEW

**Comment by Shredder121** [comment]
So the build fails because?
Did you hand count the result of the query? Or is something else wrong?

**Comment by timowest** [comment]
I think EclipseLink handles implict joins differently from Hibernate.

**Comment by Shredder121** [comment]
I think this looks fine.
@johnktims What do you think?

**Comment by johnktims** [comment]
I would like the tests to assert something about the order of the data instead of just looking at the size.

**Comment by Shredder121** [comment]
Oh that sounds good yes.
Who's going to do it?

**Comment by Shredder121** [comment]
I can do it, but I was wondering if we want Hamcrest for the tests.
It makes tests focused on ordering of elements clearer.

**Pull request merged**
