### PR TITLE
Collections: Failure of setting up classpath for javac in case of run…

### PR DESCRIPTION
**Pull request by viktorzub**
…ning in Spring Boot on Ubuntu and MacOS

I have tried this, but it work's only on redhat linux, still doesn't work on macos

code taken from https://github.com/querydsl/codegen/pull/43/files
code should be focused to fix https://github.com/querydsl/querydsl/issues/2964

Can some one review and help to develop proper fix

### CODE REVIEW

**Comment by jwgmeligmeyling** [comment]
I'll have a look tonight (CEST)

**Comment by jwgmeligmeyling** [comment]
Apparently it also doesn't work on Ubuntu Linux, at least not on Java 11. (Hence the CI failure). I'll do some more testing locally.

**Comment by viktorzub** [comment]
@jwgmeligmeyling any updates here? I also still not able to make it work at macos(

**Comment by jwgmeligmeyling** [comment]
Could you try using the ecj compiler as a workaround?

**Comment by jwgmeligmeyling** [comment]
This approach is still system dependent and has issues on Java 11.

I think we should deprecate the `JDKEvaluatorFactory` and instead encourage the use of `ECJEvaluatorFactory`. Under JRE's, this evaluator factory should be selected by default.

**Comment by viktorzub** [comment]
@jwgmeligmeyling i was not able to make it work with ECJ compiller with java 11 also(

**Pull request closed without merging**
