### PR TITLE
Checkstyle modernization

### PR DESCRIPTION
**Pull request by F43nd1r**
**Dependency upgrades:**
 - Checkstyle 6.6 -> 8.42, Update xml for new version
 - Checkstyle Maven Plugin 2.15 -> 3.1.2

**Fixed Rules Violations:**
 - Removed redundant modifiers
 - Renamed variables ending in `_`
 - Whitespace Fixes

### CODE REVIEW

**Comment by jwgmeligmeyling** [comment]
Hadn't I bumped Checkstyle to 8.x in the Java 11 branch already? I remember Checkstyle not working at all there prior to upgrading. Or was that reverted?

**Comment by F43nd1r** [comment]
It is bumped there as well. But it mostly disables rules instead of porting them. I probably should've based it off that. I'll resolve the conflicts once java 11 is merged.

**Comment by jwgmeligmeyling** [comment]
@F43nd1r Please update with master (Java 11 has been merged)

**Comment by F43nd1r** [comment]
@jwgmeligmeyling updated and tested locally. CI doesn't seem to run?

**Comment by jwgmeligmeyling** [comment]
Thanks for all your efforts @F43nd1r

**Pull request merged**
