### PR TITLE
Improve Scala usage

### PR DESCRIPTION
**Pull request by timowest**
backport of https://github.com/querydsl/querydsl/pull/1242

### CODE REVIEW

**Comment by timowest** [comment]
@Shredder121 @johnktims Is this good as well? The main PR is also merged. 

Or shall we see a positive review comment on the main PR also as the OK for the backport PR?

**Comment by johnktims** [comment]
This looks fine to me, but I'll admit that I'm not very familiar with Scala.

I think one review should suffice so long as the backport isn't significantly different.

**Comment by Shredder121** [comment]
Yes, that is why backports generally can be merged within the 2 day mark, since the first PR is already merged.
Note that a review of backwards compatibility is necessary sometimes.

**Comment by timowest** [comment]
Ok, let's do so. I am also for it.

**Pull request merged**
