### PR TITLE
Add support for multiple schemas

### LINKED ISSUE #1766: querydsl-maven-plugin to support multiple schemas at once
Add property to querydsl-maven-plugin to support multiple schemas at once.

Discussion
https://groups.google.com/d/msg/querydsl/5zuxYrhxz2U/say3FqpUBQAJ

Some suggestions:
```xml
<configuration>
    ....
    <schemaPattern>RAD,FOO,BAR</schemaPattern>
</configuration>
```

```xml
<configuration>
    ...
    <schemaPatterns>
        <schemaPattern>RAD</schemaPattern>
        <schemaPattern>FOO</schemaPattern>
        <schemaPattern>BAR</schemaPattern>
    </schemaPatterns>
</configuration>
``` 

PS: I'm using oracle 11gR2

Thank you.

### PR DESCRIPTION
**Pull request by timowest**
Fixes #1766

### CODE REVIEW

**Comment by Shredder121** [comment]
We also need a test for `schemas` and `patterns` together.

**Comment by Shredder121** [comment]
To me this looks good.

**Comment by natros** [comment]
I tried this change in a project that I'm working on and the maven configuration got smaller :) Does this takes into account the typeMapping in case of having different tables with the same name across schemas?

**Comment by timowest** [comment]
@natros Could you provide a configuration example?

**Comment by Shredder121** [comment]
It seems there is a schema inheritance, `RFID` has a parent schema `GAL`.
Once you tell it to export just `RFID`, a foreign key can't be generated it seems.

**Comment by natros** [comment]
When using ` <schemaToPackage>true</schemaToPackage>` the beans are correctly generated. Only one User classe instead of two.

https://github.com/natros/querydsl-test/tree/schema-to-package

**Pull request merged**
