### PR TITLE
Unify dependency versions

### LINKED ISSUE #1981: AbstractMethodError thrown by org.hibernate.internal.SessionFactoryImpl.<init> when upgrading from Spring Boot 1.3 to 1.4 RC1
Hi,

I tried to upgrade springboot from 1.3 to 1.4 and I get this same error. As someone pointed out there's a problem with the hibernate dependencies.
I thought that the same is happening with queryDsl as it uses different hibernate versions in different dependencies :
querydsl-apt -> 4.2.0.Final
querydsl-jpa -> 4.3.11.Final

How can I track this? 
Should querydDSL upgrade its dependencies to the latest?

reference link with same issue but difference depency.
[http://stackoverflow.com/questions/38596003/abstractmethoderror-thrown-by-org-hibernate-internal-sessionfactoryimpl-init-w/38599681#38599681](url)

And the issue I opened in springboot:

[url](https://github.com/spring-projects/spring-boot/issues/6525)

Thanks

### PR DESCRIPTION
**Pull request by timowest**
Fixes #1981

### CODE REVIEW

**Comment by Shredder121** [comment]
How about slowly moving all occurrences of dependencies to `dependencyManagement`?
Then we can just touch the root pom to bump versions, and we are less likely to miss occurrences.

Just an idea though.

**Comment by timowest** [comment]
Good idea, can we do it in an additional PR though?

**Comment by Shredder121** [comment]
Looks good anyway. :+1:

And that is fine with me.

**Comment by rmordillo-witbooking** [comment]
:+1: thanks @timowest

**Comment by Shredder121** [comment]
Do you think we can we backport this @timowest?

**Pull request merged**
