### PR TITLE
Improve backwards compatibility

### PR DESCRIPTION
**Pull request by timowest**
The remaining log is

```
Class com.querydsl.sql.Configuration
 Deprecated Method registerTableOverride, desc (Lcom/querydsl/sql/SchemaAndTable;Lcom/querydsl/sql/SchemaAndTable;)Lcom/querydsl/sql/SchemaAndTable;, access public
 Added Method setDynamicNameMapping, desc (Lcom/querydsl/sql/namemapping/NameMapping;)V, access public
 Deprecated Method registerSchemaOverride, desc (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;, access public
 Deprecated Method registerColumnOverride, desc (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;, access public
 Deprecated Method registerColumnOverride, desc (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;, access public
 Deprecated Method registerTableOverride, desc (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;, access public
 Deprecated Method registerTableOverride, desc (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Lcom/querydsl/sql/SchemaAndTable;, access public
 Deprecated Method registerTableOverride, desc (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;, access public
Class com.querydsl.sql.SQLBindings
 Deprecated Method getBindings, sig ()Lcom/google/common/collect/ImmutableList<Ljava/lang/Object;>;, desc ()Lcom/google/common/collect/ImmutableList;, access public
 Added Method getNullFriendlyBindings, sig ()Ljava/util/List<Ljava/lang/Object;>;, desc ()Ljava/util/List;, access public
 Added Method <init>, sig (Ljava/lang/String;Ljava/util/List<Ljava/lang/Object;>;)V, desc (Ljava/lang/String;Ljava/util/List;)V, access public
 Deprecated Method <init>, sig (Ljava/lang/String;Lcom/google/common/collect/ImmutableList<Ljava/lang/Object;>;)V, desc (Ljava/lang/String;Lcom/google/common/collect/ImmutableList;)V, access public
Class com.querydsl.sql.SQLListenerContext
 Added Method getAllSQLBindings, sig ()Ljava/util/Collection<Lcom/querydsl/sql/SQLBindings;>;, desc ()Ljava/util/Collection;, access abstract public
 Added Method getSQLBindings, desc ()Lcom/querydsl/sql/SQLBindings;, access abstract public
Class com.querydsl.sql.SQLTemplates
 Added Method isRequiresSchemaInWhere, desc ()Z, access final public
Class com.querydsl.sql.dml.AbstractSQLDeleteClause
 Added Class , access abstract public super synchronized
Class com.querydsl.sql.dml.AbstractSQLInsertClause
 Added Class , access abstract public super synchronized
Class com.querydsl.sql.dml.AbstractSQLUpdateClause
 Added Class , access abstract public super synchronized
Class com.querydsl.sql.dml.SQLDeleteClause
 Changed Class , access 
Class com.querydsl.sql.dml.SQLInsertClause
 Changed Class , access 
Class com.querydsl.sql.dml.SQLUpdateClause
 Changed Class , access 
Class com.querydsl.sql.mssql.AbstractSQLServerQuery
 Added Class , access abstract public super synchronized
Class com.querydsl.sql.mssql.SQLServerQuery
 Changed Class , access 
Class com.querydsl.sql.mysql.AbstractMySQLQuery
 Added Class , access abstract public super synchronized
Class com.querydsl.sql.mysql.MySQLQuery
 Changed Class , access 
Class com.querydsl.sql.namemapping.ChainedNameMapping
 Added Class , access public super synchronized
Class com.querydsl.sql.namemapping.ChangeLetterCaseNameMapping
 Added Class , access public super synchronized
Class com.querydsl.sql.namemapping.ChangeLetterCaseNameMapping.LetterCase
 Added Class , access enum final public super synchronized
Class com.querydsl.sql.namemapping.NameMapping
 Added Class , access abstract interface public
Class com.querydsl.sql.namemapping.PreConfiguredNameMapping
 Added Class , access public super synchronized
Class com.querydsl.sql.oracle.AbstractOracleQuery
 Added Class , access abstract public super synchronized
Class com.querydsl.sql.oracle.OracleQuery
 Changed Class , access 
Class com.querydsl.sql.postgresql.AbstractPostgreSQLQuery
 Added Class , access abstract public super synchronized
Class com.querydsl.sql.postgresql.PostgreSQLQuery
 Changed Class , access 
Class com.querydsl.sql.teradata.AbstractTeradataQuery
 Added Class , access abstract public super synchronized
Class com.querydsl.sql.teradata.TeradataQuery
 Changed Class , access 
```

### CODE REVIEW

**Comment by Shredder121** [comment]
So it should be fixed now, yes? To me the remaining log looks not problematic.
[The JLS already mentions that most of the changes that happened should be backwards compatible](https://docs.oracle.com/javase/specs/jls/se7/html/jls-13.html):

> - Moving a method upward in the class hierarchy.
> - Inserting new class or interface types in the type hierarchy.

But thanks for fixing this, Timo!

**Comment by timowest** [comment]
The checker is unfortunately a bit stricter concerning inheritance tree changes, so a few classes needed to be excluded from the checks.

Could you approve this then? I will try to do the release this weekend.

**Comment by Shredder121** [comment]
Looks good to me, yes!

**Comment by Shredder121** [comment]
@timowest I think we needed a `castRequired` in these bridge methods.

**Comment by Shredder121** [comment]
etc.
```
java.lang.VerifyError: Bad return type
Exception Details:
  Location:
    com/querydsl/sql/dml/AbstractSQLDeleteClause.limit(J)Lcom/querydsl/sql/dml/SQLDeleteClause; @15: areturn
  Reason:
    Type 'com/querydsl/sql/dml/AbstractSQLDeleteClause' (current frame, stack[0]) is not assignable to 'com/querydsl/sql/dml/SQLDeleteClause' (from method signature)
  Current Frame:
    bci: @15
    flags: { }
    locals: { 'com/querydsl/sql/dml/AbstractSQLDeleteClause', long, long_2nd, '[Z' }
    stack: { 'com/querydsl/sql/dml/AbstractSQLDeleteClause' }
```

**Pull request merged**
