### PR TITLE
Replace deprecated class usage

### PR DESCRIPTION
**Pull request by timowest**
backport https://github.com/querydsl/querydsl/issues/1320

### CODE REVIEW

**Comment by johnktims** [comment]
The only other instances of deprecated API usage that I can find outside of the tests is all the calls to `SqlTemplates#SqlTemplates(String quoteStr, char escape, boolean useQuotes)`. Do you want to correct that here?

**Comment by timowest** [comment]
Not here, since that is not external API. Also it will require quite a lot of work.

**Comment by johnktims** [comment]
Okay. This PR looks good to me.

**Comment by Shredder121** [comment]
@johnktims yes, that is more of a reminder that the keyword quoting support is only the 'default SQL' keywords.
It is quite a lot of work to get it right for all the Templates.

**Pull request merged**
