### PR TITLE
Fix date trunc mappings

### LINKED ISSUE #1155: Can't trunc date to current day in Oracle
In Oracle `TRUNC(some_date)` will remove the time element from the date. `TRUNC(some_date, 'day')` however, will return the start of the week, which is what you get if you call `SQLExpressions.datetrunc(DatePart.day, someDateTimePath)`. IMO, this is poor naming on Oracle's part, however I would have expected the SQL to manifest to be `TRUNC(some_date, 'dd')`, or for `DatePart` to include further values so that `TRUNC(some_date, 'dd')` was attainable, or better yet that `TRUNC(some_date)` with no time component was supported.

### PR DESCRIPTION
**Pull request by timowest**
Fixes #1155

### CODE REVIEW

**Comment by timowest** [comment]
References:
* Oracle http://www.techonthenet.com/oracle/functions/trunc_date.php
* Teradata http://www.info.teradata.com/HTMLPubs/DB_TTU_14_00/index.html#page/SQL_Reference/B035_1145_111A/ch07.077.134.html#ww18264021
* DB2 http://www-01.ibm.com/support/knowledgecenter/SSEPGG_9.7.0/com.ibm.db2.luw.sql.ref.doc/doc/r0053634.html?cp=SSEPGG_9.7.0%2F2-10-3-2-167

**Comment by Shredder121** [comment]
I think this looks good.
Have you also looked at the other databases, or is their support already good?

**Comment by timowest** [comment]
I will try to improve the tests for these mappings to be sure.

**Comment by timowest** [comment]
I'll still improve the mappings a bit in the evening

**Comment by timowest** [comment]
When this is finalized I can backport this as well.

**Comment by timowest** [comment]
@Shredder121 There was a request for more comments from your side that got hidden through a rebase I guess. I also didn't fully understand what you meant. Could you recomment, if it is still relevant.

**Comment by Shredder121** [comment]
What I meant was adding a simple line comment that restates what it did in English, or in symbols.
It is not that relevant, but I just figured it might help.

**Comment by Shredder121** [comment]
At least it looks good.

So I can merge it if you don't think the comments are necessary.

**Comment by timowest** [comment]
Wait, I will add some comments. You are right, without comments some patterns might feel quite cryptic in a few months.

**Comment by timowest** [comment]
I added some comments for some cryptic patterns, although there is common pattern as you will see.

**Comment by Shredder121** [comment]
Yes I agree, that is exactly what I want to protect us from.
Something that works perfectly now, 'could be improved' later.
I also agree that the pattern is common, it's just appending parts to each other, but it's better to document some things for later. ;)

So then I will merge it.

**Pull request merged**
