### PR TITLE
Querydsl 4.2.0

### PR DESCRIPTION
**Pull request by timowest**

### CODE REVIEW

**Comment by Shredder121** [comment]
Could we merge Reuben's PR to include it?

**Comment by timowest** [comment]
sure, can you link it?

**Comment by Shredder121** [comment]
https://github.com/querydsl/querydsl/milestone/50

these two need merging, that's at least what would be good to release.
https://github.com/querydsl/querydsl/pull/2253
https://github.com/querydsl/querydsl/pull/2236

**Comment by Shredder121** [comment]
:+1:
Then should be good

**Pull request merged**
