### PR TITLE
Improve quoting

### PR DESCRIPTION
**Pull request by timowest**
Fixes https://github.com/querydsl/querydsl/issues/1355

### CODE REVIEW

**Comment by timowest** [comment]
@johnktims @Shredder121 Is this good to merge?

**Comment by johnktims** [comment]
Do we also need to quote `top` as mentioned in the ticket?

**Comment by timowest** [comment]
I think that would be a different PR. That would be defining the reserved keywords, which is different from the general escaping logic.

**Comment by johnktims** [comment]
Then I think this is ready to be merged.

**Pull request merged**
