### PR TITLE
hibernate5.2-compatibility

### PR DESCRIPTION
**Pull request by ask4gilles**
Attempt to fix https://github.com/querydsl/querydsl/issues/1917 and
https://github.com/querydsl/querydsl/issues/2264

### CODE REVIEW

**Comment by ask4gilles** [comment]
It was an attempt to see what it gives on CI. I'm not avare of all the implications for other projects than jpa...

**Comment by Shredder121** [comment]
Well, there's hibernate search, but also we'll need to clean up the poms.

**Comment by ask4gilles** [comment]
Hi @Shredder121, any update on your PR? This one is green... without hibernate-search, which would require a complete rewrite I guess... How can we move forward with this? I'm still currently stuck upgrading to Spring boot 2 in my projects using querydsl. If nothing moves, I'll have to find something else than querydsl. Thanks for your update.

**Comment by Shredder121** [comment]
Need to update master with version updates, remove deprecated code (since new major bump), clean up poms, fix new deprecation warnings.
So far I've done 1, 3, and 4 a bit, but also need to clean up my stashes regarding checkstyle.
I went through the new checkstyle violations yesterday evening, I can stash it again and work on Querydsl 5 tonight.

**Comment by ask4gilles** [comment]
Nice! Keep me posted, I'll leave this one open if you need some inspiration (?). Feel free to close it when you are done :)

**Comment by ask4gilles** [comment]
Hi @Shredder121, where are you on the way to 5.0?

**Comment by ask4gilles** [comment]
Ok, thanks for the update! :)

**Comment by Shredder121** [comment]
And you thanks for the poke! 👍

**Comment by ask4gilles** [comment]
Hi @Shredder121 , sorry to put the pressure but do you have any ETA? :) :)

**Comment by Shredder121** [comment]
ETA no, but I should have a bit more time the coming week(s).
You are free to poke me more than once a week(since pre-weekend stuff), although the comments might get cluttered a bit :/

**Comment by ask4gilles** [comment]
hi @Schredder121, any news ?

**Comment by Shredder121** [comment]
Working on a few branches at the same time, sorry.

**Comment by ask4gilles** [comment]
I personally use Spring boot which gives me the hibernate dependency. (There is a ticket to upgrade to 5.3 bit this won't happen any time soon... https://github.com/spring-projects/spring-boot/issues/11725) Regarding your question, maybe @vladmihalcea has a clue?

**Comment by jpimag** [comment]
Hello,
I built a modified 5.3.1.final version of hibernate-core in order to include last development on 5.1 compatibility  (https://hibernate.atlassian.net/browse/HHH-12651) (5.3.2 not yet released) .
Session::createQuery compatibility is restored but, now, I'm facing an exception on queries using parameters.

`java.lang.IllegalArgumentException: Could not locate named parameter [1], expecting one of []
	at org.hibernate.query.internal.ParameterMetadataImpl.getNamedParameterDescriptor(ParameterMetadataImpl.java:218)
	at org.hibernate.query.internal.ParameterMetadataImpl.getQueryParameter(ParameterMetadataImpl.java:187)
	at org.hibernate.query.internal.QueryParameterBindingsImpl.getBinding(QueryParameterBindingsImpl.java:188)
	at org.hibernate.query.internal.AbstractProducedQuery.setParameter(AbstractProducedQuery.java:494)
	at org.hibernate.query.internal.AbstractProducedQuery.setParameter(AbstractProducedQuery.java:107)
	at com.querydsl.jpa.hibernate.HibernateUtil.setValue(HibernateUtil.java:91)
	at com.querydsl.jpa.hibernate.HibernateUtil.setConstants(HibernateUtil.java:79)
	at com.querydsl.jpa.hibernate.AbstractHibernateQuery.createQuery(AbstractHibernateQuery.java:105)
	at com.querydsl.jpa.hibernate.AbstractHibernateQuery.createQuery(AbstractHibernateQuery.java:97)
	at com.querydsl.jpa.hibernate.AbstractHibernateQuery.fetch(AbstractHibernateQuery.java:174)
` 
We make important use of query-dsl in our project, we appreciate this library and we highly appreciate a new compatible version :-) Thanks

**Comment by ask4gilles** [comment]
@jpimag since nothing is moving, we are unfortunately planning to not use querydsl any more in our projects.

**Comment by andygoossens** [comment]
@jpimag I experienced the same problem. I have created a separate issue for it: https://github.com/querydsl/querydsl/issues/2326

**Comment by kdebski85** [comment]
@Shredder121 
Maybe instead of Hibernate 5.2, we should focus on 5.3 compatibility.
This sounds as an easier task.
Hibernate 5.3 restored some compatibility.
On the other hand, it changed positional parameters support, which caused https://github.com/querydsl/querydsl/issues/2326

Could we please have querydsl 5 with Hibernate 5.3 support anytime soon?
Maybe the scope of querydsl 5 can be limited to make the release in the near future.

Currently querydsl prevents from using Spring 5, Spring Boot 2, Hibernate 5.2 and 5.3.

**Comment by Shredder121** [comment]
That indeed would be a good idea, I'll see when I can dedicate some time on an evening again.

**Comment by kespinosa05** [comment]
Hi @Shredder121 any progress here

**Comment by johnktims** [comment]
Querydsl is now compatible with hibernate 5.

**Pull request closed without merging**
