### PR TITLE
Fix schema handling

### LINKED ISSUE #1977: MySQL null schema
Hello, 

I'm using maven with querydsl sql (4.1.3) generator to generate some classes from a mysql 5.7.13 database

The basic maven configuration I'm using is

``` xml
 <jdbcDriver>com.mysql.jdbc.Driver</jdbcDriver>
              <jdbcUrl>jdbc:mysql://127.0.0.1:3306/maxmail_cliente_123?useSSL=false</jdbcUrl>
              <jdbcUser>root</jdbcUser>
              <jdbcPassword>root123</jdbcPassword>
              <packageName>foo.bar.entities.maxmailclient</packageName>
              <targetFolder>${project.build.sourceDirectory}</targetFolder>
              <exportBeans>true</exportBeans>
              <schemaToPackage>true</schemaToPackage>
```

And in the generated Q\* files, the schema is set to "null". From what I can see the mysql jdbc driver uses the catalog information instead of schema.

``` java
 public QMaxmailingClientes(String variable) {
        super(MaxmailingClientes.class, forVariable(variable), "null", "maxmailing_clientes");
        addMetadata();
    }

    public QMaxmailingClientes(String variable, String schema, String table) {
        super(MaxmailingClientes.class, forVariable(variable), schema, table);
        addMetadata();
    }

    public QMaxmailingClientes(Path<? extends MaxmailingClientes> path) {
        super(path.getType(), path.getMetadata(), "null", "maxmailing_clientes");
        addMetadata();
    }

    public QMaxmailingClientes(PathMetadata metadata) {
        super(MaxmailingClientes.class, metadata, "null", "maxmailing_clientes");
        addMetadata();
    }
```

I'm using printSchema in the template because I need to access different databases in a single connection

``` java
SQLTemplates templates = MySQLTemplates.builder()
        .printSchema()
        .build();
```

but I'm getting errors:

```
com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'null.maxmailing_lists' doesn't exist
```

Most of the time I'm using oracle and everything is perfect, but not with mysql.

### PR DESCRIPTION
**Pull request by timowest**
Fixes #1977

### CODE REVIEW

**Comment by Shredder121** [comment]
Just wondering, why `progress`?

**Comment by timowest** [comment]
I'll add some tests and am also considering moving this to SQLTemplates

**Comment by Shredder121** [comment]
Good call. Sounds good.

**Comment by jCube1980** [comment]
Is there a workaround, without this fix, for resolving null schemas in MySql? If not, can this be merged to master?

**Comment by efried** [comment]
Is there any word on when this update will be released?
I am using MySQL Connector/J 8 and QueryDSL 4.2.1 and I am having the same issue as appears [here](https://github.com/querydsl/querydsl/issues/2347)
The Schema Pattern looks to be broken for a similar reason in that ```md.getTables(null, schemaPattern, tablePattern, types);``` will return all schemas.

**Comment by balazs-zsoldos** [comment]
+1

**Review by oxygenecore — APPROVED** [review]

**Pull request closed without merging**
