### PR TITLE
Add test

### PR DESCRIPTION
**Pull request by timowest**
Related to #1982

### CODE REVIEW

**Comment by timowest** [comment]
@Shredder121 @johnktims @robertandrewbain Could I get a review?

**Comment by Shredder121** [comment]
What are the semantics of `order by xxx is (not) null`? Is that even valid JPQL?

**Comment by timowest** [comment]
It's ordering by an boolean expression, it's not valid JPQL, but supported by the JPA providers.

**Comment by Shredder121** [comment]
So would it make sense to add that as a test case?

**Comment by Shredder121** [comment]
:+1: I mean, it looks fine, but doesn't really reflect the issue.

**Comment by timowest** [comment]
You are right, it's misleading.

**Pull request closed without merging**
