### PR TITLE
Fix modulo normalization

### PR DESCRIPTION
**Pull request by timowest**
Fixes https://github.com/querydsl/querydsl/issues/1759

### CODE REVIEW

**Comment by johnktims** [comment]
Looks good.

**Comment by Shredder121** [comment]
Keep in mind that since it now also uses `%` to look for operations, it triggers earlier (when using like `%`, it will look for operations, so maybe some more tests?)

**Comment by timowest** [comment]
good point with the like patterns, I'll add some tests

**Comment by Shredder121** [comment]
Also, If I add this:

```java
@Test
@Category(Performance.class)
public void Performance2() throws Exception {
    Runner.run("NormalizationTest Performance2", new Benchmark() {
        @Override
        public void run(int times) throws Exception {
            for (int i = 0; i < times; i++) {
                Normalization.normalize("select name from product where description like '%on sale%'");
            }
        }
    });
}
```

Then my test output becomes this:

```
- - NormalizationTest Performance2 5,230 s
- - NormalizationTest Performance 49,50 ms
```

Do we do anything about that? Or do we think that correctness is key and take the hit?

**Comment by timowest** [comment]
The fix for various issues related to normalization is in Querydsl 4. I'd say we focus on correctness for Querydsl 3. But easy improvements to performance can of course be applied.

**Comment by Shredder121** [comment]
Okay, just wanted you to be aware of that.

**Comment by Shredder121** [comment]
And on that note, LGTM.
Shall I merge it or does someone else want to?

**Comment by timowest** [comment]
You can merge it.

**Comment by Shredder121** [comment]
I figured maybe John's hands were itching to merge some PRs, but I'll do this one then.

**Pull request merged**
