### PR TITLE
Fix String cast mapping

### LINKED ISSUE #1106: String cast generates invalid SQL using EclipseLink and MySQL
Eclipselink uses the template 'cast({0} varchar(255))' for the STRING_CAST function.  This does not work when the underlying database is MySQL.  MySQL uses the type 'char' rather than 'varchar'.  The correct template in this situation would be 'cast({0} char(255))'.

### PR DESCRIPTION
**Pull request by timowest**
Fixes #1106

### CODE REVIEW

**Comment by timowest** [comment]
The ToChar operator doesn't seem to work as documented.

**Comment by Shredder121** [comment]
Now `.append("test")` chains don't work at all anymore.
Maybe add a trim?

**Comment by timowest** [comment]
I added now a test for `append` usage.

**Comment by timowest** [comment]
And added now the necessary trim as well. At least HSQLDB and Derby required it.

**Comment by Shredder121** [comment]
That is indeed what I noticed.

**Comment by Shredder121** [comment]
So, are you content with the outcome? Shall I merge then?

**Comment by timowest** [comment]
Yes, this is fine with me.

**Pull request merged**
