### PR TITLE
Bump codegen version

### PR DESCRIPTION
**Pull request by timowest**

### CODE REVIEW

**Comment by johnktims** [comment]
I verified that codegen's version was incremented but I can't tell if anything else was changed in the file since it was reformatted. If that's all that changed, this looks fine to me.

**Comment by timowest** [comment]
I'll make a cleaner commit instead.

**Comment by johnktims** [comment]
That's better. Thanks.

It looks good to me.

**Comment by Shredder121** [comment]
What's the deal with changing the last lines everytime, what is intellij set to?
Other than that, it looks good to me as well.

**Comment by timowest** [comment]
I am not sure which setting causes it.

**Pull request merged**
