### PR TITLE
Update reference docs

### PR DESCRIPTION
**Pull request by timowest**

### CODE REVIEW

**Comment by timowest** [comment]
@johnktims @Shredder121 This also needs to be merged for the 4.0 release. Sorry that it took me so long to update it.

**Comment by Shredder121** [comment]
Do you feel confident to also update the Korean snippets?

**Comment by timowest** [comment]
That's a little tricky, since I updated also the texts.

**Comment by Shredder121** [comment]
Okay, it's your call.
I haven't really looked at *all* the snippets (specifically if you missed any), but to me it looks good.

**Comment by timowest** [comment]
Well, we can't really publish the 4.0 code with the 3.* docs. I am a bit unhappy with the native query examples, but otherwise I think it's good.

**Pull request merged**
