### PR TITLE
Fixed the links in the examples chapter in the README.md

### PR DESCRIPTION
**Pull request by bcubk**
I noticed that the links in the README.md were wrong. I've created a pull request with a fix

### CODE REVIEW

**Comment by Shredder121** [comment]
Hello,
Thank you very much for the fix!
I hope it isn't much to ask, but could you push a new commit, with [ci skip] on the next line?
That way, we can immediately merge it, since it doesn't conflict with the build matrix.

**Comment by bcubk** [comment]
sure :)

**Comment by Shredder121** [comment]
I meant you could replace that one commit with the same commit, like `git commit --amend`.

**Comment by bcubk** [comment]
Oh, sorry. I misunderstood you. I hope the commit is now correct.

**Comment by Shredder121** [comment]
No it's okay, communication is bidirectional, so I also apologize.
Thanks for your contribution!

**Comment by Shredder121** [comment]
@timowest what is your opinion actually:
The GitHub repository landing page is the master branch, do you think we have to keep the documentation in sync?

**Comment by timowest** [comment]
I don't think we have to backport fixes to the md files. At least the priority is not so high.

**Pull request merged**
