### PR TITLE
Use querydsl-parent

### LINKED ISSUE #1132: querydsl-root POM changes
As querydsl-root's parent is 'mysema-source', it inherits its properties.

This means that the `<organisation>` of Querydsl is still 'Mysema Ltd'.

It should be a better idea to replace (or eliminate) 'mysema-source' as parent.

### PR DESCRIPTION
**Pull request by timowest**
Fixes #1132

### CODE REVIEW

**Comment by johnktims** [comment]
Nice. Looks good.

**Comment by Shredder121** [comment]
Missed this one.
Looks good. I'll merge these.

Do we know yet what Intellij does with the prolog and last line?

**Comment by timowest** [comment]
No, I haven't yet investigated why that change happens

**Comment by Shredder121** [comment]
I'll merge these anyway, we'll find it one day.

**Pull request merged**
