### PR TITLE
Make Expression types instantiable

### PR DESCRIPTION
**Pull request by timowest**

### CODE REVIEW

**Comment by timowest** [comment]
@johnktims @Shredder121 @robertandrewbain Do you see problems with this approach? Maybe we could make the constructors of the *Expression types protected?

**Comment by Shredder121** [comment]
Depends on what you want to achieve.
Do you want to not directly extend *Expression types?

**Comment by timowest** [comment]
I thought that directly providing the support to wrap expressions would be beneficial.

**Comment by timowest** [comment]
But then I realized that there are serious drawbacks in this approach, e.g. a wrapped path won't be a path anymore.

**Comment by timowest** [comment]
I'll provide direct instantiation in a different (and safer) way later.

**Pull request closed without merging**
