### PR TITLE
Fix listener execution

### LINKED ISSUE #1479: Insert operation doesn't fire listener executed() for non-batch operations
SQLInsertClause.executeWithKeys()

 334:             listeners.preExecute(context);
 335:             stmt.executeUpdate();
 336:             listeners.preExecute(context);   <---- Should this not be executed() ?

### PR DESCRIPTION
**Pull request by timowest**
Fixes #1479

### CODE REVIEW

**Comment by Shredder121** [comment]
To me this looks good.

**Comment by johnktims** [comment]
The fix looks correct but I think there should be a test.

**Comment by Shredder121** [comment]
Hmm, yes you're right.
I could make something if you want.

**Comment by timowest** [comment]
Ok

**Comment by Shredder121** [comment]
I haven't yet had time to finish the tests, but is that a blocker for this issue? @johnktims

**Comment by johnktims** [comment]
The fix looks correct and I'd like to see it in the release so I'll just merge it and we can add some tests later.

**Pull request merged**
