### PR TITLE
Remove reference to junit.framework

### PR DESCRIPTION
**Pull request by johnktims**

### CODE REVIEW

**Comment by Shredder121** [comment]
You could also add a checkstyle configuration for [`IllegalImport`](http://checkstyle.sourceforge.net/config_imports.html#IllegalImport) if you feel like it.
Or if you think that's not necessary that's fine too.

```xml
<module name="IllegalImport">
    <property name="illegalPkgs" value="junit.framework, ..." />
</module>

```

**Comment by johnktims** [comment]
Good idea. I'll add that.

**Comment by Shredder121** [comment]
Looks good :smile:

**Comment by timowest** [comment]
Looks good

**Pull request merged**
