### PR TITLE
Add clear method to DML clauses

### LINKED ISSUE #1785: StoreClause: Clear Batches on Execute
Would it be possible to clear batches on execute, so that it's easy to configure when to flush? Currently we get OutOfMemoryError because of a large batch and the simplest course of action would be just to flush more often.

### PR DESCRIPTION
**Pull request by timowest**
Fixes #1785

### CODE REVIEW

**Comment by timowest** [comment]
TODO: tests

**Comment by Shredder121** [comment]
Looks good.

**Comment by Shredder121** [comment]
I was thinking of maybe extracting a common AbstractDMLTest class, but that's not really better I think?

**Comment by timowest** [comment]
> I was thinking of maybe extracting a common AbstractDMLTest class, but that's not really better I think?

Yes, that could be a followup PR if we want to test something more consistenly.

**Comment by johnktims** [comment]
Looks good, Timo.

**Pull request merged**
