### PR TITLE
Extend Checkstyle checks

### PR DESCRIPTION
**Pull request by timowest**

### CODE REVIEW

**Comment by johnktims** [comment]
Would it be better to move the querydsl_checks*.xml files to src/main/resources?

Also, I'd also prefer to be a little more specific with the name of the querydsl_checks.xml file. Maybe querydsl_checks_base.xml or common? Otherwise it looks like there are two main files.

**Comment by timowest** [comment]
Yes, these changes make sense.

**Comment by timowest** [comment]
Is this good to merge? This is so massive that I'd prefer to merge it ASAP.

**Comment by Shredder121** [comment]
Yes, since it is essentially only reports from checkstyle that are fixed I think this is good to merge.

**Pull request merged**
