### PR TITLE
Add the "server" parameter (alternative to jdbcUser and jdbcPassword)

### PR DESCRIPTION
**Pull request by mdiazf**
Add the *server* parameter (the id of a `<server>` from settings.xml) as
an alternative to jdbcUser and jdbcPassword parameters.

### CODE REVIEW

**Comment by timowest** [comment]
Thanks for the PR! Could you take a look at the Checkstyle errors and fix them?

**Comment by mdiazf** [comment]
Fixed!

**Comment by timowest** [comment]
Great, unnecessary finals could also be removed from local variables.

**Comment by Shredder121** [comment]
Just a question, is it necessary to add a setter for the server parameter?
I think for consistency's sake adding it anyway is a good idea.

Other than that, it looks good to me!

**Comment by mdiazf** [comment]
Code style and consistency discrepancies fixed.

**Comment by timowest** [comment]
Looks good.

**Comment by johnktims** [comment]
Looks good. Thanks for the contribution, @mdiazf.

**Pull request merged**
