### PR TITLE
Add johnktims to developers

### PR DESCRIPTION
**Pull request by timowest**

### CODE REVIEW

**Comment by Shredder121** [comment]
Do we also add him to the reference documentation?

**Comment by timowest** [comment]
That's done here https://github.com/querydsl/querydsl/commit/4e8ea378cd4d835bb8cbaac7b5cc6084de6aea5e

**Comment by Shredder121** [comment]
Ah yes, I see now.

**Comment by timowest** [comment]
@johnktims Can this be merged? ;)

**Comment by johnktims** [comment]
Oh I guess so... ;)

**Pull request merged**
