### PR TITLE
Querydsl 4.2.0

### PR DESCRIPTION
**Pull request by timowest**

### CODE REVIEW

**Comment by Shredder121** [comment]
What's the build failure?
I'm on my phone currently.

**Comment by Shredder121** [comment]
Oh I see that Travis died, ok.

**Comment by timowest** [comment]
Good to merge?

**Comment by Shredder121** [comment]
👍 
Not quite sure what is wrong with Travis, thought it was related to some status update that day.
But if it builds anyway I'd say release it.

**Pull request merged**
