### PR TITLE
SQLServer2012Templates for SQL Servers newer than 2012

### PR DESCRIPTION
**Pull request by lpandzic**
Currently the logic is to fallback to regular SQLServerTemplates which I believe is not ideal.

### CODE REVIEW

**Comment by jwgmeligmeyling** [comment]
Looks good! Can you fix the checkstyle error?

I hate Checkstyle incredibly but there is not much I can do about it now 😄

**Comment by lpandzic** [comment]
Fixed.

**Comment by jwgmeligmeyling** [comment]
Merged. Thanks for your contribution! We're about to release 5.0 soon, which will incorporate this patch.

**Comment by lpandzic** [comment]
Thanks!

**Pull request merged**
