### PR TITLE
Remove deprecated methods

### PR DESCRIPTION
**Pull request by timowest**

### CODE REVIEW

**Comment by timowest** [comment]
Docs have been now updated as well

**Comment by Shredder121** [comment]
There are still some occurrences of 'full join' in the docs. That makes 4 in total.
```xml
    <title>Using joins</title>

    <para>Querydsl supports the following join variants in JPQL: inner join, join, left
      join and full join. Join usage is typesafe, and follows the following pattern:
    </para>
```


```xml
    <para>
      <emphasis>innerJoin, join, leftJoin, fullJoin, on:</emphasis>
      조인 부분을 추가한다. 조인 메서드에서 첫 번째 인자는 조인 소스이고,
      두 번재 인자는 대상(별칭)이다.
    </para>
```

There is one more, but it is in the Korean docs, in Korean of course.
Since we don't speak Korean, we might need to ask @madvirus if he could help us.

**Comment by timowest** [comment]
@madvirus Could you look at the korean docs? There seems to one mentioning of full join left.

@Shredder121 I updated the docs again.

**Comment by Shredder121** [comment]
Yes, after that one we got them all I think.

**Comment by timowest** [comment]
I externalized the review of the korean docs

**Comment by Shredder121** [comment]
Yes, that seems like a good choice.

**Comment by timowest** [comment]
@Shredder121 Is this good to merge now?

**Comment by Shredder121** [comment]
Yes, the Korean docs is the only thing that was missing.
So I'll merge this.

**Pull request merged**
