### PR TITLE
Normalize line endings to lf

### PR DESCRIPTION
**Pull request by Shredder121**
This should also prevent Windows line ending issues.

We don't really need anything with `crlf` line endings, do we?
Thoughts? Problem cases?

### CODE REVIEW

**Comment by robertandrewbain** [comment]
Looks good to me.

**Comment by timowest** [comment]
Looks good

**Comment by johnktims** [comment]
I'd remove the outdated performance documents (e.g. querydsl-collections/doc/perf-20090313.txt).

**Comment by Shredder121** [comment]
Done.

**Pull request merged**
