### PR TITLE
Update JTSGeometryExpressions: added transform

### PR DESCRIPTION
**Pull request by JWGmeligMeyling**
Added the transform operation to JTSGeometryExpressions

### CODE REVIEW

**Comment by timowest** [comment]
Transform is already available in JTSGeomtryExpression, so no need to duplicate it as a static method.

**Comment by JWGmeligMeyling** [comment]
How would I do that with a `ConstantImpl.create(geometry)`?

**Comment by JWGmeligMeyling** [comment]
Nevermind, I missed that one. Thanks!

**Comment by timowest** [comment]
You could transform the JTS geometry via JTS tools before using it in a query, I think that makes more sense.

**Comment by JWGmeligMeyling** [comment]
After scrolling a bit through all the available classes, I still wasn't able to find how to get from a `Constant` expression to a `JTSGeometryExpression`. I ended up writing:

```java
	private class JTSConstantGeometry<T extends Geometry> extends JTSGeometryExpression<T> {

		public JTSConstantGeometry(T constant) {
			super(ConstantImpl.create(constant));
		}

		@Nullable
		@Override
		public <R, C> R accept(Visitor<R, C> v, C context) {
			return v.visit((ConstantImpl<Geometry>) mixin, context);
		}
	}
```

Am I still miserably missing something? :wink:

**Comment by timowest** [comment]
@robertandrewbain Could this be covered also in https://github.com/querydsl/querydsl/pull/1682 ?

The relevant factory classes are `GeometryExpressions` and `JTSGeometryExpressions`.

**Comment by robertandrewbain** [comment]
@timowest, yes, I believe that it could. I'll add that tonight.

**Comment by timowest** [comment]
Closing this in favor of a constant -> typed expression conversion approach.

**Pull request closed without merging**
